export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const EDIT_COLLECTION = 'EDIT_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const CREATE_CLIP = 'CREATE_CLIP';
export const EDIT_CLIP = 'EDIT_CLIP';
export const DELETE_CLIP = 'DELETE_CLIP';
export const MARK_AS_READ = 'MARK_AS_READ';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
